apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"creationTimestamp":"2020-09-06T10:23:50Z","labels":{"run":"testpod11"},"managedFields":[{"apiVersion":"v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:labels":{".":{},"f:run":{}}},"f:spec":{"f:externalTrafficPolicy":{},"f:ports":{".":{},"k:{\"port\":90,\"protocol\":\"TCP\"}":{".":{},"f:port":{},"f:protocol":{},"f:targetPort":{}}},"f:selector":{".":{},"f:run":{}},"f:sessionAffinity":{},"f:type":{}}},"manager":"kubectl-expose","operation":"Update","time":"2020-09-06T10:23:50Z"},{"apiVersion":"v1","fieldsType":"FieldsV1","fieldsV1":{"f:spec":{"f:ports":{"k:{\"port\":90,\"protocol\":\"TCP\"}":{"f:nodePort":{}}}}},"manager":"kubectl-edit","operation":"Update","time":"2020-09-06T10:47:20Z"}],"name":"testpod","namespace":"default","resourceVersion":"12643","selfLink":"/api/v1/namespaces/default/services/testpod","uid":"de5b1cda-697a-4276-979d-b6418cef7500"},"spec":{"clusterIP":"10.102.2.36","externalTrafficPolicy":"Cluster","ports":[{"nodePort":31111,"port":90,"protocol":"TCP","targetPort":80}],"selector":{"run":"testpod"},"sessionAffinity":"None","type":"NodePort"},"status":{"loadBalancer":{}}}
  creationTimestamp: "2020-09-06T10:23:50Z"
  labels:
    run: testpod11
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels: {}
      f:spec:
        f:externalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":90,"protocol":"TCP"}:
            .: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:run: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: kubectl-expose
    operation: Update
    time: "2020-09-06T10:23:50Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          f:run: {}
      f:spec:
        f:ports:
          k:{"port":90,"protocol":"TCP"}:
            f:nodePort: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2021-02-03T10:26:24Z"
  name: testpod
  namespace: default
  resourceVersion: "1059739"
  selfLink: /api/v1/namespaces/default/services/testpod
  uid: de5b1cda-697a-4276-979d-b6418cef7500
spec:
  clusterIP: 10.102.2.36
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31111
    port: 90
    protocol: TCP
    targetPort: 80
  selector:
    run: testpod
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
